### ISSUE TITLE
pov demonstration 

### ISSUE THREAD

**Issue by mkeyno** [woundedlion/pov#1]
hi buddy , do you have any video or demonstration of your code

**Comment by woundedlion** [comment]
Hey, here's some videos. Hard to capture with my phone because the camera's
framerate interferes with the effect, causing flicker and other artifacts.
Suffice it to say it looks much better in person. Are you attempting
something similar?

https://www.dropbox.com/s/ppamd45tk2y6rzq/20160222_211447.mp4?dl=0

https://www.dropbox.com/s/382uwa8f63rr5in/20160222_211620.mp4?dl=0

https://www.dropbox.com/s/sw8e4pts1mf6xtu/20160222_211711.mp4?dl=0

https://www.dropbox.com/s/2oshrphxvh1eikx/20160222_211840.mp4?dl=0

https://www.dropbox.com/s/dxwprh6ebbc2su4/20160221_192401.mp4?dl=0

https://www.dropbox.com/s/kghwm038dw8doaw/20160222_211811.mp4?dl=0

**Comment by mkeyno** [comment]
hi @woundedlion  , I'm so sorry to draw issue for my question but I really appreciated for your opinion , actually I'm trying to use fastLED lib to drive my APA102 for POV project , I've tried to implement it with ESP, but frame rate is so slow for 144 APA102 pixel,
my approach is to read pixel data from SPIFF file without closing it , but result beyond my expectation very slow even with 160Mhz clock
following is the serial output and loop code
i=0 New Image=1.bin duration=4
[frame]1076598
[frame]1043446
[frame]1044003
[frame]1043555
i=1 New Image=2.bin duration=4
[frame]1057822
[frame]1052909
[frame]1052453
i=2 New Image=3.bin duration=4
[frame]1067164
[frame]1042669
[frame]1043549
[frame]1042468
i=3 New Image=4.bin duration=4
[frame]1059210
[frame]1044297
[frame]1044701
[frame]1044550
i=4 New Image=5.bin duration=4
[frame]1059668
[frame]1042478
[frame]1043678
[frame]1043824
i=5 New Image= duration=0
FILE NOT OPEN
i=0 New Image=1.bin duration=4
[frame]1075868
[frame]1044087
[frame]1044103
[frame]1044578
i=1 New Image=2.bin duration=4
[frame]1059307
[frame]1052474
[frame]1052181
i=2 New Image=3.bin duration=4
[frame]1067527
[frame]1042757
[frame]1042843
[frame]1043076
i=3 New Image=4.bin duration=4
[frame]1058051
[frame]1045418
[frame]1046048
[frame]1045034
i=4 New Image=5.bin duration=4
[frame]1059883
[frame]1043249
[frame]1043334
[frame]1043710
i=5 New Image= duration=0
FILE NOT OPEN
i=0 New Image=1.bin duration=4

loop code
void loop()
{

if(!SHOW) server.handleClient();

webSocket.loop();

if(SHOW)
{
if( (millis()- OpenlastTime) > DURATION[image_index]*1000L )
{
FILe.close();
image_index++;
if(image_index>IMAGE_NUM) image_index=0;

   Serial.print(F(" i="));  Serial.print(image_index); 
  Serial.print(F(" New Image="));  Serial.print(IMAGES[image_index]);
  Serial.print(F(" duration="));  Serial.println(DURATION[image_index]);

   FILe=SPIFFS.open("/SHOW/"+IMAGES[image_index], "r");
  if(!FILe) Serial.println("FILE NOT OPEN");
  OpenlastTime=millis();
}
if(!Start_new_round && (micros()-lastLineShow)> lineInterval)
                  {
                  int i=0,j=0;
                  byte rgb=0,r,g,b; 
                  while(FILe.available()&& i< (NUM_LEDS*3))
                                                            {
                                                            byte c=FILe.read();
                                                                 if(rgb==0) r=byte(c);
                                                            else if(rgb==1) g=byte(c);
                                                            else if(rgb==2) b=byte(c);
                                                            else           { rgb=0;
                                                                             leds[j] = CRGB(r,g,b);
                                                                             j++; 
                                                                             }
                                                            rgb++;  
                                                            i++;
                                                            }
                  FastLED.show(); lastLineShow=micros();  
                  Current_imageLine++;  
                  }

FastLED.show(); lastLineShow=micros(); }
if(Current_imageLine >= IMAGES_LINES)

{
Serial.print("[frame]"); Serial.println((micros()-lastFrameShow));
Current_imageLine = 0;
lastFrameShow=micros();
Start_new_round=false;
FILe.close();
FILe=SPIFFS.open("/SHOW/"+IMAGES[image_index], "r");
}

}

}

**Comment by woundedlion** [comment]
Hi @mkeyno,
Without knowing how your POV display works, I might suggest the following:

Measure:

1) Take the total time in which you hope to draw the full image and divide by the number of columns in your display. This will give you a target duration to draw a single column.

2) Print the time in microseconds to draw a single column in your loop. This will tell you how far off from your target time you are.

3) Profile your draw loop with some logs and see where the routine is spending time.

Optimize:

1) Reading a single byte at a time from the SD card for each pixel seems potentially very slow. Can you read the whole file into an array outside of your draw loop then loop through the array in memory to draw?

2) How fast is FILE.available()? You could loop from 0 to FILE.size() - 1 instead of calling available() once for each byte. For safety, check the file size, something like assert(FILE.size() == NUM_LEDS \* 3 \* NUM_COLUMNS); to make sure it has all your data.

3) Get rid of i and i++ in your loop, it's not doing anything for you.

4) You are needlessly copying each byte twice. I don't know without looking at the assembly if the compiler is optimizing that away for you. Maybe just do leds[j] = CRGB(FILE.read(), FILE.read(), FILE.read());

5) Use hardware SPI if it is available on our board.

6) I'm not familiar with the ESP, its performance characteristics, memory capacity, etc. but working with the teensy 3.2 has been great. APA102 is plenty fast (as is FastLED) so your problem is likely logic or hardware. Consider better hardware?
